steps:

- id: go_test
  name: "gcr.io/cloud-builders/go"
  args: ["test","./src"]

- id: go_build
  name: "gcr.io/cloud-builders/go"
  args: ["build","./src/app.go"]

- id: build_docker
  name: "gcr.io/cloud-builders/docker"
  args: ["build","-t","gcr.io/$PROJECT_ID/desafio-ci:latest","."]

images: ["gcr.io/$PROJECT_ID/desafio-ci:latest"]